name: Install dependencies

description: 'Set up a Node.js environment and install dependencies'

runs:
    using: 'composite'
    steps:
        - uses: actions/setup-node@v3
          with:
              node-version: 18
              cache: 'npm'
        - run: npm ci
          shell: bash
