name: CI

on: [push, pull_request]

jobs:
    test:
        name: Test
        needs: install_dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/install_dependencies
            - run: npm run test

    build:
        name: Build
        needs: install_dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/install_dependencies
            - run: npm run build
