name: CI

on: [push, pull_request]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/setup.yml
            - run: npm run test

    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/setup.yml
            - run: npm run build
