name: Install dependencies

on: workflow_call

jobs:
    install_dependencies:
        name: Install dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'
            - run: npm ci
